---
- hosts: sentries
  become: yes
  any_errors_fatal: true
  tasks:
    - name: Update repositories cache and install prerequisites
      apt:
        pkg:
          - curl
          - acl
        update_cache: yes
    - import_role:
        name: ansible-role-golang
    - import_role:
        name: bluzelle
    - name: Include sentry task
      include_role:
        name: bluzelle
        tasks_from: sentry
...
